services:
  floci:
    image: floci/floci:1.5.14
    user: root
    environment:
      FLOCI_HOSTNAME: floci
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
